# MQTT over TLS with the self signed certificate, the broker itself only listens
# on a unix socket and holds no certificate
server {
    listen 8883 ssl;

    include snippets/stream-ssl.conf;
    ssl_certificate /usr/local/nginx/conf/ssl/arpi_app.crt;
    ssl_certificate_key /usr/local/nginx/conf/ssl/arpi_app.key;

    proxy_pass mqtt_broker;
    
    # CRITICAL LATENCY FIXES:
    proxy_buffer_size 4k;
    proxy_timeout 1h;
    proxy_connect_timeout 5s;
    
    # Disable buffering so packets flush instantly
    tcp_nodelay on;
}
