# override file for mosquitto.service
# fixing permissions on the socket file for the mosquitto user and www-data group
[Service]
RuntimeDirectory=mosquitto
RuntimeDirectoryMode=0755

ExecStartPost=+/bin/sh -c 'for _ in $(seq 1 50); do if [ -S /run/mosquitto/mosquitto.sock ]; then chown mosquitto:www-data /run/mosquitto/mosquitto.sock && chmod 660 /run/mosquitto/mosquitto.sock && exit 0; fi; sleep 0.1; done; exit 1'
