"""empty message

Revision ID: 1d2b1100bda5
Revises: 4f8202bcfbba
Create Date: 2024-02-06 07:49:45.122287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2b1100bda5'
down_revision = '4f8202bcfbba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ui_order', sa.Integer(), nullable=True))
        batch_op.alter_column('channel',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('channel',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('ui_order')

    # ### end Alembic commands ###
