"""Sensor channel type and error state

Revision ID: 43a24ca7b746
Revises: e72781fbd520
Create Date: 2025-09-12 21:36:25.852469

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "43a24ca7b746"
down_revision = "e72781fbd520"
branch_labels = None
depends_on = None


channel_types = sa.Enum("basic", "normal", "channel_a", "channel_b", name="channel_types")


def upgrade():
    # add channel types
    channel_types.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensor", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("channel_type", channel_types, nullable=False, server_default="normal")
        )
        batch_op.add_column(
            sa.Column(
                "error", sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()
            )
        )
        batch_op.alter_column(
            "alert",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            server_default=sa.sql.expression.false(),
        )
        batch_op.alter_column(
            "enabled",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            server_default=sa.sql.expression.true(),
        )
        batch_op.alter_column(
            "deleted",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            server_default=sa.sql.expression.false(),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensor", schema=None) as batch_op:
        batch_op.alter_column("deleted", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("enabled", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("alert", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.drop_column("error")
        batch_op.drop_column("channel_type")

    # ### end Alembic commands ###

    # drop channel types
    channel_types.drop(op.get_bind(), checkfirst=True)
