"""User mcp key

Revision ID: 4df9df54d928
Revises: 710d6b5f7f5b
Create Date: 2026-02-08 18:47:18.095287

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4df9df54d928"
down_revision = "710d6b5f7f5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mcp_key", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("mcp_key")

    # ### end Alembic commands ###
