"""empty message

Revision ID: 4f8202bcfbba
Revises: c180da8f93a4
Create Date: 2024-01-28 18:49:56.224434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8202bcfbba'
down_revision = 'c180da8f93a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.Enum('area', 'system', 'button', name='output_trigger_type'), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('button_type', sa.Enum('impulse', 'switch', name='output_button_type'), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('default_state', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('output')
    op.execute("DROP TYPE public.output_button_type;")
    op.execute("DROP TYPE public.output_trigger_type;")
    # ### end Alembic commands ###
