"""Sensor contact type

Revision ID: 5169b6306036
Revises: 43a24ca7b746
Create Date: 2025-09-14 21:07:29.470289

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5169b6306036"
down_revision = "43a24ca7b746"
branch_labels = None
depends_on = None

sensor_contact_types = sa.Enum("NO", "NC", name="sensor_contact_types")


def upgrade():
    sensor_contact_types.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensor", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "sensor_contact_type",
                sa.Enum("NO", "NC", name="sensor_contact_types"),
                nullable=False,
                server_default="NC",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensor", schema=None) as batch_op:
        batch_op.drop_column("sensor_contact_type")

    # ### end Alembic commands ###
    sensor_contact_types.drop(op.get_bind(), checkfirst=True)
