"""Sensor EOL count

Revision ID: 710d6b5f7f5b
Revises: 5169b6306036
Create Date: 2025-09-15 22:10:21.480154

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "710d6b5f7f5b"
down_revision = "5169b6306036"
branch_labels = None
depends_on = None

eol_count_enum = sa.Enum("single", "double", name="sensor_eol_count")


def upgrade():
    eol_count_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensor", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("sensor_eol_count", eol_count_enum, nullable=False, server_default="single")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensor", schema=None) as batch_op:
        batch_op.drop_column("sensor_eol_count")

    # ### end Alembic commands ###
    eol_count_enum.drop(op.get_bind(), checkfirst=True)
