"""empty message

Revision ID: 865d107141bb
Revises: 1d2b1100bda5
Create Date: 2024-02-08 08:34:23.615757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865d107141bb'
down_revision = '1d2b1100bda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
