"""empty message

Revision ID: 88226184f921
Revises: 5bccaa26edb4
Create Date: 2024-01-11 14:46:33.279608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88226184f921'
down_revision = '5bccaa26edb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ui_hidden', sa.Boolean(), nullable=False, server_default="false"))
        batch_op.drop_column('ui_hide')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ui_hide', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.drop_column('ui_hidden')

    # ### end Alembic commands ###
