"""empty message

Revision ID: aa035fa3c9a6
Revises: 865d107141bb
Create Date: 2024-02-08 09:57:39.622786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa035fa3c9a6'
down_revision = '865d107141bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.drop_column('button_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.add_column(sa.Column('button_type', postgresql.ENUM('impulse', 'switch', name='output_button_type'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
