"""empty message

Revision ID: d3663af259a5
Revises: b525bd3091af
Create Date: 2024-03-21 11:48:53.874753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3663af259a5'
down_revision = 'b525bd3091af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('silent', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('suppression', sa.String(), nullable=False))

    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('silent_alarm', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('monitor_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monitor_threshold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_column('monitor_threshold')
        batch_op.drop_column('monitor_size')
        batch_op.drop_column('silent_alarm')
        batch_op.drop_column('name')

    with op.batch_alter_table('alert_sensor', schema=None) as batch_op:
        batch_op.drop_column('suppression')
        batch_op.drop_column('silent')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
