name: CI / Test

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    paths:
      - '**.py'
      - 'Taskfile.yml'
      - '.github/workflows/ci-test.yml'
  push:
    paths:
      - '**.py'
      - 'Taskfile.yml'
      - '.github/workflows/ci-test.yml'
    branches:
      - 'main'
      - 'dev_*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    name: Run ${{ matrix.name }} tests
    if: >-
      ${{
        (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'dev_')) ||
        (github.event_name == 'push' && !contains(github.event.head_commit.message, 'GitHub Actions: bump version'))
      }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: unit
            task: test-unit
          - name: functional-arm
            task: test-functional-arm
          # - name: functional-installer
          #   task: test-functional-installer
          - name: functional-options
            task: test-functional-options
          # - name: functional-output
          #   task: test-functional-output
          - name: functional-power-outage
            task: test-functional-power-outage
          - name: functional-sensitivity
            task: test-functional-sensitivity
          - name: functional-silent-alert
            task: test-functional-silent-alert
          - name: functional-startup
            task: test-functional-startup

    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v6

      - name: Cache Python packages 📦
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ runner.os }}-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            pip-cache-${{ runner.os }}-

      - name: Setup Python 🐍
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'

      - name: Install dependencies 📦
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/task/task/setup.deb.sh' | sudo -E bash
          sudo apt update && sudo apt install -y jq
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install Task 🛠️
        uses: go-task/setup-task@v2

      - name: Run tests 🔍
        run: |
          task create-environment
          if [ "$RUNNER_DEBUG" = "1" ]; then
            PYTEST_ADDOPTS="-vv --setup-show --maxfail=1" task ${{ matrix.task }}
          else
            task ${{ matrix.task }}
          fi

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-reports-${{ matrix.name }}
          overwrite: true
          path: |
            junit.xml
            coverage.xml
          if-no-files-found: warn

  Publish:
    name: Publish test reports
    if: >-
      ${{
        always() &&
        (
          (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'dev_')) ||
          (github.event_name == 'push' && !contains(github.event.head_commit.message, 'GitHub Actions: bump version'))
        )
      }}
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Checkout repository 🛎️
        uses: actions/checkout@v6
        
      - name: Download test reports
        uses: actions/download-artifact@v8
        with:
          path: test-reports
          
      - name: Merge and deduplicate reports
        run: |
          reportgenerator \
            -reports:"test-reports/test-reports-*/coverage.xml" \
            -targetdir:"coverage-merged" \
            -reporttypes:"Cobertura"

      - name: Publish test results
        uses: dorny/test-reporter@v3
        with:
          name: pytest
          reporter: python-xunit
          path: test-reports/**/junit.xml

      - name: Generate coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage-merged/Cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          indicators: true
          output: file

      - name: Report Code Coverage Summary
        run: |
          echo "## Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
          cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Fail when tests failed
        if: needs.Test.result != 'success'
        run: exit 1
