name: CI / Test

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'dev_*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    name: Run tests
    if: >-
      ${{
        github.event_name == 'pull_request' ||
        (github.event_name == 'push' && !contains(github.event.head_commit.message, 'GitHub Actions: bump version'))
      }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v6

      - name: Cache Python packages 📦
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ runner.os }}-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            pip-cache-${{ runner.os }}-

      - name: Setup Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies 📦
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/task/task/setup.deb.sh' | sudo -E bash
          sudo apt update && sudo apt install -y jq task
          curl -LsSf https://astral.sh/uv/install.sh | sh
          task create-environment

      - name: Run tests 🔍
        run: |
          if [ "$RUNNER_DEBUG" = "1" ]; then
            task test-debug
          else
            task test
          fi
